pipeline {
  stages {
    stage('Build') {
      steps {
        sh 'mvn clean package || npm install'
      }
    }
    stage('Test') {
      steps {
        sh 'mvn test || npm test'
      }
    }
    stage('Quality') {
      steps {
        sh 'sonar-scanner'
      }
    }
    stage('Docker') {
      steps {
        sh 'docker build .'
      }
    }
  }
}
